### ISSUE TITLE
Riferimento iusse #9

### ISSUE THREAD

**Issue by gianpaolot** [italia/spid-shibboleth-proxy-docker#20]
Buongiorno scrivo per conto di PA Evolution che ha avuto mandato da parte di Arpacal di sviluppare l'accesso SPID al loro portale. Faccio riferimento alla iusse#9 aperta da scubla88. Seguendo le indicazioni presenti:

1. ho aggiornato il certificato sulla vecchia versione (il certificato ho preso quello dell'ultima commit sul master). Il problema  "unable to locate metadata for identity provider spid" si è risolto ma mi ritorna l'errore che veniva specificato iusse#9 per gli IDP: namirial, tim, infocer,poste,sielte, mentre funziona per gli IDP
Aruba,SpidItalia,Intesa,AGID TEST.

2. ho scaricato l'ultimo progetto, fatte le configurazione con le modifiche apportate, ma non riesco a chiamare nessun IDP, rimando sempre sulla pagina di errore , nei log scrive
 

> Shibboleth handler invoked at an unconfigured location., referer: https://servizionline.arpacal.it/ibcauthenticationgateway/spidlogin

Riuscite a darmi indicazione o sul punto 1 o sul punto 2

Grazie
Saluti
Pa Evolution

**Comment by gianpaolot** [comment]
Buongiorno, 
il problema sul punto due è stato risolto, era un mio errore di configurazione e del link invocato. per adesso anche sulla nuova versione per gli IPD 1. namirial, tim, infocer,poste,sielte persiste il problema specificato da scubla88 una volta aggiornate i certificati

**Comment by psmiraglia** [comment]
Salve @gianpaolot, credo di non aver capito il suo problema. Potrebbe essere piu' chiaro? Grazie.

**Comment by psmiraglia** [comment]
Chiuso per inattivita'.
