### ISSUE TITLE
Discovery automatico IdP e migrazione v1.1.0

### ISSUE THREAD

**Issue by scubla88** [italia/spid-shibboleth-proxy-docker#21]
Buongiorno,
all'interno della nostra soluzione abbiamo implementato un discovery automatico degli IdP basandoci su un vostro servizio: https://registry.spid.gov.it/api/identity-providers
Tale servizio non presenta l'IdP provider Lepida e inoltre sembra che ora tale servizio sia stato disattivato, è così? Nel caso in cui fosse stato disattivato quale è il metodo ufficiale per gestire correttamente un discovery automatico degli identity provider?

Stiamo valutando la migrazione del progetto alla versione più aggiornata, la v1.1.0, ma vorremmo capire se tale versione gestisce tutte le verifiche della richiesta (AuthnRequest) e della risposta (Response) previste per la verifica tecnica da parte di AgID.

Grazie,
Fabio Scubla

**Comment by scubla88** [comment]
Buongiorno,
abbiamo notato che il servizio https://registry.spid.gov.it/api/identity-providers oggi funziona correttamente, ma manca l'IdP Lepida.
Verrà aggiunto?

Grazie,
Fabio Scubla

**Comment by psmiraglia** [comment]
> Tale servizio non presenta l'IdP provider Lepida e inoltre sembra che ora tale servizio sia stato disattivato, è così? Nel caso in cui fosse stato disattivato quale è il metodo ufficiale per gestire correttamente un discovery automatico degli identity provider?

La cosa  e' stata gia' segnalata ed e' attualmente in fase di gestazione. Essendo questo un argomento non direttamente collegato questo repository, la pregherei di far riferimento a spid.tech@agid.gov.it per ulteriori informazioni e/o chiarimenti sul tema.

> Stiamo valutando la migrazione del progetto alla versione più aggiornata, la v1.1.0, ma vorremmo capire se tale versione gestisce tutte le verifiche della richiesta (AuthnRequest) e della risposta (Response) previste per la verifica tecnica da parte di AgID.

Per quanto riguarda la `AuthnRequest`, il componente gia' rispetta tutte le specifiche SPID. Riguardo la validazione della `Response`, alcuni controlli devono ancora essere implementati nel backend dall'utilizzatore. A riguardo, suggerisco di leggere l'issue #16 dove la tematica e' stata trattata nel dettaglio.

**Comment by scubla88** [comment]
Buongiorno,
ringrazio per la risposta.

> La cosa e' stata gia' segnalata ed e' attualmente in fase di gestazione. Essendo questo un argomento non direttamente collegato questo repository, la pregherei di far riferimento a [spid.tech@agid.gov.it](mailto:spid.tech@agid.gov.it) per ulteriori informazioni e/o chiarimenti sul tema.

Abbiamo già inviato una mail e scritto nel Forum Italia, ma al momento non abbiamo ricevuto risposta, quindi per ora gli IdP li stiamo gestendo manualmente.

> Per quanto riguarda la `AuthnRequest`, il componente gia' rispetta tutte le specifiche SPID. Riguardo la validazione della `Response`, alcuni controlli devono ancora essere implementati nel backend dall'utilizzatore. A riguardo, suggerisco di leggere l'issue #16 dove la tematica e' stata trattata nel dettaglio.

Va bene, proveremo a guardare la issue, ma a tal proposito non c'è una documentazione o delle linee guida per sapere esattamente tutto quello che c'è da implementare nel backend?

Grazie per l'assistenza,
Fabio

**Comment by psmiraglia** [comment]
> Va bene, proveremo a guardare la issue, ma a tal proposito non c'è una documentazione o delle linee guida per sapere esattamente tutto quello che c'è da implementare nel backend?

I controlli da applicare nel backend sono quelli relativi all'`Assertion`. In particolare, ottenendo l'asserzione in formato raw (come indicato nell'issue #16) dovete implementare tutti i controlli definiti nelle [regole tecniche SPID](https://www.agid.gov.it/sites/default/files/repository_files/circolari/spid-regole_tecniche_v1.pdf) e nei vari [Avvisi](https://www.agid.gov.it/it/piattaforme/spid/avvisi-spid).
